In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import classification_report, confusion_matrix

from sklearn import preprocessing
from sklearn.model_selection import train_test_split

from sklearn.neural_network import MLPClassifier

from sklearn import datasets, metrics

In [7]:
df= pd.read_csv('class-knn.csv')

In [8]:
df.head()

class  x1  x2  x3
0  class1   1  11  51
1  class1   2  11  51
2  class1   3  22  51
3  class1   4  55  52
4  class1   1  12  55

In [11]:
x=df.drop('class',axis=1)
y=pd.DataFrame(df, columns = ['class'])

In [13]:
x2= pd.DataFrame(preprocessing.scale(x, with_mean=False))
x2.columns=x.columns
x=x2

In [14]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [22]:
classifier=MLPClassifier(hidden_layer_sizes=(5, 5, 5), max_iter=1000)
classifier.fit(X_train,y_train.values.ravel())

/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(5, 5, 5), learning_rate='constant',
              learning_rate_init=0.001, max_iter=1000, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [23]:
y_pred = classifier.predict(X_test)

In [24]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[4 0 0]
 [0 2 0]
 [0 0 2]]
              precision    recall  f1-score   support

      class1       1.00      1.00      1.00         4
      class2       1.00      1.00      1.00         2
      class3       1.00      1.00      1.00         2

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8



In [25]:
classifier

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(5, 5, 5), learning_rate='constant',
              learning_rate_init=0.001, max_iter=1000, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)